services:
  fuseki:
    image: stain/jena-fuseki
    restart: unless-stopped
    ports:
      - "3030:3030"
    volumes:
      - ./docker-data:/fuseki
    environment:
      - ADMIN_PASSWORD=admin1@

